### PR TITLE
W2 - hieucap - Create recyclerview

### PR DESCRIPTION
**Pull request by at-hieucap**
#### Related issues (Optional)
Task #21 

#### Description (Required)
- [x] Create recyclerview

### CODE REVIEW

**Comment by at-huongnguyen** [comment]
@at-hieucap 
Please resolve conflict

**Comment by at-hieucap** [comment]
@at-huongnguyen please review for me ,
Thank you so much!

**Comment by at-hieucap** [comment]
@at-huongnguyen ,  please review for me ,
Thank you so much!

**Comment by at-hieucap** [comment]
@at-huongnguyen , please review for me ,
Thank you so much!

**Comment by at-hieucap** [comment]
@at-vinhhuynh  I fix finish , please review for me
Thank you so much!

**Pull request merged**
